import {
  LayoutDashboard,
  Cpu,
  Building2,
  Users,
  BarChart3,
  Settings,
  HelpCircle,
  LogOut,
  Search,
  Moon,
  Sun,
  Bell as Notifications,
  ChevronRight,
  MoreVertical,
  Plus,
  TrendingUp,
  Timer,
  Wrench,
  Activity,
  AlertTriangle,
  CheckCircle2,
  ArrowRight,
  ShieldCheck,
  BadgeCheck,
  Camera,
  Languages,
  Globe,
  Database,
  Cloud,
  Zap,
  Key,
  Filter,
  Download,
  Calendar,
  UserPlus,
  Lock,
  Mail,
  Eye,
  EyeOff,
  Factory,
  Menu,
  X
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Machines: Cpu,
  BusinessUnits: Building2,
  Users: Users,
  Reports: BarChart3,
  Settings: Settings,
  Support: HelpCircle,
  Logout: LogOut,
  Search: Search,
  Moon: Moon,
  Sun: Sun,
  Notifications: Notifications,
  ChevronRight: ChevronRight,
  MoreVertical: MoreVertical,
  Plus: Plus,
  TrendingUp: TrendingUp,
  Timer: Timer,
  Wrench: Wrench,
  Activity: Activity,
  AlertTriangle: AlertTriangle,
  CheckCircle2: CheckCircle2,
  ArrowRight: ArrowRight,
  ShieldCheck: ShieldCheck,
  BadgeCheck: BadgeCheck,
  Camera: Camera,
  Languages: Languages,
  Globe: Globe,
  Database: Database,
  Cloud: Cloud,
  Zap: Zap,
  Key: Key,
  Filter: Filter,
  Download: Download,
  Calendar: Calendar,
  UserPlus: UserPlus,
  Lock: Lock,
  Mail: Mail,
  Eye: Eye,
  EyeOff: EyeOff,
  Factory: Factory,
  Menu: Menu,
  X: X,
};
